/** Validated deterministic mock requests projected from generation-node state. */

import type {
  FlowNodeType,
  GenerationModelDefinition,
  GenerationNodeType,
  GenerationSettingValue,
} from '@talelabs/flows'
import type {
  CanvasNode,
  FlowGenerationPreviewOutput,
} from '../editor/flow-canvas-types'

import { evaluateGenerationContract, resolveLlmState } from '@talelabs/flows'

/** Immutable text-generation request consumed by the deterministic mock runtime. */
export interface LlmMockRequest {
  /** Canonical image Asset ids supplied to the LLM operation. */
  imageAssetIds: readonly string[]
  /** Trimmed system-style instructions captured from the node. */
  instructions: string
  /** Discriminator for text preview generation. */
  kind: 'text'
  /** Translation key used to name the preview output. */
  labelKey: string
  /** Resolved locale captured when the request is planned. */
  locale: string
  /** Catalog contract version pinned by the node. */
  modelContractVersion: string
  /** Canonical creative model id pinned by the node. */
  modelId: string
  /** Resolved catalog operation selected for execution. */
  operationId: string
  /** Trimmed prompt captured from the node. */
  prompt: string
  /** Normalized settings sorted into deterministic key order. */
  settings: Readonly<Record<string, GenerationSettingValue>>
  /** Mock request schema version used by fingerprinting and replay. */
  templateVersion: 1
}

/** Immutable media-generation request consumed by the deterministic mock runtime. */
export interface MediaMockRequest {
  /** Connected upstream source descriptors captured in stable order. */
  connectedSources: readonly string[]
  /** Canonical input Asset ids captured in stable order. */
  inputAssetIds: readonly string[]
  /** Discriminator for media preview generation. */
  kind: 'media'
  /** Translation key used to name the preview output. */
  labelKey: string
  /** Resolved locale captured when the request is planned. */
  locale: string
  /** Output media family generated by the node. */
  mediaType: 'audio' | 'image' | 'video'
  /** Catalog contract version pinned by the node. */
  modelContractVersion: string
  /** Canonical creative model id pinned by the node. */
  modelId: string
  /** Node receiving the preview result. */
  nodeId: string
  /** Persisted generation-node family. */
  nodeType: FlowNodeType
  /** Resolved catalog operation selected for execution. */
  operationId: string
  /** Runtime value type emitted through the node output handle. */
  outputValueType: 'AudioSet' | 'ImageSet' | 'VideoSet'
  /** Normalized settings sorted into deterministic key order. */
  settings: Readonly<Record<string, GenerationSettingValue>>
  /** Mock request schema version used by fingerprinting and replay. */
  templateVersion: 1
  /** Trimmed inline text captured by semantic input slot. */
  textInputs: Readonly<Record<string, string>>
}

/** Deterministic mock-runtime request supported by current generation nodes. */
export type GenerationMockRequest = LlmMockRequest | MediaMockRequest

function canonicalSettings(
  settings: Readonly<Record<string, GenerationSettingValue>>,
) {
  return Object.fromEntries(Object.entries(settings).toSorted(([left], [right]) => (
    left.localeCompare(right)
  )))
}

/** Toolbar/output adapter metadata used while projecting generation requests. */
export const FLOW_GENERATION_PREVIEW_ADAPTERS = {
  audioGeneration: {
    kind: 'media',
    mediaType: 'audio',
    outputValueType: 'AudioSet',
  },
  imageGeneration: {
    kind: 'media',
    mediaType: 'image',
    outputValueType: 'ImageSet',
  },
  llm: { kind: 'text', outputValueType: 'Text' },
  musicGeneration: {
    kind: 'media',
    mediaType: 'audio',
    outputValueType: 'AudioSet',
  },
  soundEffectGeneration: {
    kind: 'media',
    mediaType: 'audio',
    outputValueType: 'AudioSet',
  },
  speechGeneration: {
    kind: 'media',
    mediaType: 'audio',
    outputValueType: 'AudioSet',
  },
  videoGeneration: {
    kind: 'media',
    mediaType: 'video',
    outputValueType: 'VideoSet',
  },
  voiceChanger: {
    kind: 'media',
    mediaType: 'audio',
    outputValueType: 'AudioSet',
  },
  voiceIsolation: {
    kind: 'media',
    mediaType: 'audio',
    outputValueType: 'AudioSet',
  },
} as const satisfies Record<GenerationNodeType, {
  kind: 'media' | 'text'
  mediaType?: MediaMockRequest['mediaType']
  outputValueType: FlowGenerationPreviewOutput['valueType']
}>

/** Returns a mock LLM request only when the current node contract is runnable. */
export function createLlmMockRequest(input: {
  connectionCounts: Readonly<Record<string, number>>
  imageAssetIds: readonly string[]
  instructions: string
  itemCounts: Readonly<Record<string, number>>
  locale: string
  model: GenerationModelDefinition
  node: CanvasNode
  prompt: string
}) {
  const resolution = resolveLlmState({
    connectionCounts: input.connectionCounts,
    inlineInstructions: input.instructions,
    inlinePrompt: input.prompt,
    itemCounts: input.itemCounts,
    model: input.model,
    settings: input.node.data.settings ?? {},
  })
  if (resolution.readiness !== 'ready' || !resolution.resolvedOperationId)
    return null

  return {
    imageAssetIds: [...input.imageAssetIds],
    instructions: input.instructions.trim(),
    kind: 'text',
    labelKey: input.model.labelKey,
    locale: input.locale,
    modelContractVersion: String(input.node.data.modelContractVersion),
    modelId: input.model.id,
    operationId: resolution.resolvedOperationId,
    prompt: input.prompt.trim(),
    settings: canonicalSettings(resolution.normalizedSettings),
    templateVersion: 1,
  } as const satisfies LlmMockRequest
}

/** Returns a mock media request only after the complete generation contract validates. */
export function createMediaMockRequest(input: {
  connectedSources: readonly string[]
  connectionCounts: Readonly<Record<string, number>>
  inputAssetIds: readonly string[]
  itemCounts: Readonly<Record<string, number>>
  locale: string
  model: GenerationModelDefinition
  node: CanvasNode
  operationId?: string
  settings?: Readonly<Record<string, GenerationSettingValue>>
  textInputs?: Readonly<Record<string, string>>
}) {
  const adapter = FLOW_GENERATION_PREVIEW_ADAPTERS[
    input.node.type as GenerationNodeType
  ]
  if (adapter.kind !== 'media')
    return null
  const operationId = input.operationId
    ?? String(input.node.data.operationId ?? '')
  const settings = input.settings ?? input.node.data.settings ?? {}
  const evaluation = evaluateGenerationContract({
    connectionCounts: input.connectionCounts,
    itemCounts: input.itemCounts,
    model: input.model,
    operationId,
    requireComplete: true,
    settings,
  })
  if (evaluation.issues.length > 0)
    return null

  return {
    connectedSources: [...input.connectedSources].toSorted(),
    inputAssetIds: [...input.inputAssetIds].toSorted(),
    kind: 'media',
    labelKey: input.model.labelKey,
    locale: input.locale,
    mediaType: adapter.mediaType,
    modelContractVersion: String(input.node.data.modelContractVersion),
    modelId: input.model.id,
    nodeId: input.node.id,
    nodeType: input.node.type,
    operationId,
    outputValueType: adapter.outputValueType,
    settings: canonicalSettings(settings),
    templateVersion: 1,
    textInputs: Object.fromEntries(
      ['lyrics', 'prompt']
        .map(key => [
          key,
          String(input.textInputs?.[key] ?? input.node.data[key] ?? '').trim(),
        ] as const)
        .filter(([, value]) => value.length > 0),
    ),
  } as const satisfies MediaMockRequest
}
