import type { FlowCanvasContextValue } from './flow-canvas-context'

import { useMemo } from 'react'

export function useFlowCanvasContextValue(input: FlowCanvasContextValue) {
  const {
    deleteNodes,
    duplicateNodes,
    editingImageCropNodeId,
    generationConfig,
    getAssetUpload,
    getExecutableInputCount,
    getGenerationPreview,
    getGenerationPreviewFingerprint,
    getIncompatibleGenerationEdgeCount,
    getIncompatibleGenerationEdges,
    getInputState,
    getNode,
    isRunAllRunning,
    openAssetPicker,
    openNodeOutputInspector,
    referenceData,
    retryGenerationRun,
    runAll,
    runGenerationPreview,
    setEditingImageCropNodeId,
    updateGenerationConfiguration,
    updateNodeData,
    updateNodeReference,
  } = input
  return useMemo(() => ({
    deleteNodes,
    duplicateNodes,
    editingImageCropNodeId,
    generationConfig,
    getAssetUpload,
    getExecutableInputCount,
    getGenerationPreview,
    getGenerationPreviewFingerprint,
    getIncompatibleGenerationEdgeCount,
    getIncompatibleGenerationEdges,
    getInputState,
    getNode,
    isRunAllRunning,
    openAssetPicker,
    openNodeOutputInspector,
    referenceData,
    retryGenerationRun,
    runAll,
    runGenerationPreview,
    setEditingImageCropNodeId,
    updateGenerationConfiguration,
    updateNodeData,
    updateNodeReference,
  }), [
    deleteNodes,
    duplicateNodes,
    editingImageCropNodeId,
    generationConfig,
    getAssetUpload,
    getExecutableInputCount,
    getGenerationPreview,
    getGenerationPreviewFingerprint,
    getIncompatibleGenerationEdgeCount,
    getIncompatibleGenerationEdges,
    getInputState,
    getNode,
    isRunAllRunning,
    openAssetPicker,
    openNodeOutputInspector,
    referenceData,
    retryGenerationRun,
    runAll,
    runGenerationPreview,
    setEditingImageCropNodeId,
    updateGenerationConfiguration,
    updateNodeData,
    updateNodeReference,
  ])
}
